### ISSUE TITLE
Is it possible to return a keyed address dictionary?

### ISSUE THREAD

**Issue by booherbg** [marshallford/reverse-geocoder#3]
I'm looking to keep track of stats regarding an address. Specifically I would like to store (at a minimum): City, Zip Code, State, and Country (so I can run stats on them for later).

Right now I am splitting by ',' but this can be problematic in certain cases, like when an address comes back as 'Terminal 1-Lindbergh, 4300 Glumack Dr, St Paul, MN 55111, USA' (there's a comma in the actual street name).

Combined with issue #2 this can make it a bit tricky to properly pull out city, state and zip code. 

It would be nice if there was an additional set of fields, like (just an example):

```
{
   address: 'Terminal 1-Lindbergh, 4300 Glumack Dr'
   city: 'St Paul',
   state: 'MN',
   zip_code: '55111',
   country: 'USA'
}
```

**Comment by booherbg** [comment]
Now that I think about it, it would be handy to get any other relevant info, like neighborhood or airport. Maybe this is pushing it too far... although it'd be nice to at least see what's possible
https://developers.google.com/maps/documentation/geocoding/intro

**Comment by marshallford** [comment]
This functionality is now supported via 2d87ea9. This type of information can be pulled out of responses on a per provider basis. See the `extrasPath` and `extras` config options.
